//! RtcCallSession — real WebRTC peer connection via webrtc-rs.
//!
//! This implementation uses the `webrtc-rs` crate for actual peer-to-peer
//! media transport. It implements the same interface as `SimulatedCallSession`
//! but with real DTLS-SRTP, ICE, and codec negotiation.
//!
//! Enable with the `real-webrtc` feature flag.

use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::sync::{mpsc, Mutex};
use crate::media::MediaCapture;
use crate::types::{AudioSamples, CallState, IceCandidateInit, VideoFrame};

// webrtc-rs imports
use webrtc::api::APIBuilder;
use webrtc::api::media_engine::MediaEngine;
use webrtc::api::setting_engine::SettingEngine;
use webrtc::peer_connection::peer_connection_state::RTCPeerConnectionState;
use webrtc::peer_connection::sdp::session_description::RTCSessionDescription;
use webrtc::peer_connection::configuration::RTCConfiguration;
use webrtc::peer_connection::RTCPeerConnection;
use webrtc::track::track_local::track_local_static_rtp::TrackLocalStaticRTP;
use webrtc::track::track_local::{TrackLocal, TrackLocalWriter};
use webrtc::rtp_transceiver::rtp_codec::RTCRtpCodecCapability;

// ---------------------------------------------------------------------------
// RtcCallSession
// ---------------------------------------------------------------------------

/// Insert `b=AS:<kbps>` immediately after every `m=` media section line in an
/// SDP, capping the application's send bandwidth. RFC 4566 b=AS is honored by
/// WebRTC stacks as an initial/max send bitrate; `kbps == 0` leaves the SDP
/// untouched (unbounded).
pub fn inject_b_as(sdp: &str, kbps: u64) -> String {
    if kbps == 0 {
        return sdp.to_string();
    }
    let mut out = String::with_capacity(sdp.len() + 64);
    for line in sdp.lines() {
        out.push_str(line);
        out.push('\n');
        if line.starts_with("m=") {
            out.push_str(&format!("b=AS:{kbps}\n"));
        }
    }
    out
}

pub struct RtcCallSession {
    /// Stable call identifier assigned by the daemon.
    pub call_id: String,
    pub conv_id: String,
    pub video: bool,

    /// Send-bandwidth cap in kbps (from the daemon's `call_kbps` transfer
    /// limit), applied as an SDP `b=AS:` line on every media section. `None`
    /// leaves the SDP unchanged (unbounded).
    pub max_kbps: Option<u64>,

    /// Local SDP offer/answer generated by the peer connection.
    pub local_sdp: String,

    /// Current call state (shared so the UI can observe it cheaply).
    pub state: Arc<Mutex<CallState>>,

    /// Incoming audio from the remote peer.
    pub remote_audio_rx: mpsc::Receiver<AudioSamples>,

    /// Incoming video from the remote peer. `None` for audio-only calls.
    pub remote_video_rx: Option<mpsc::Receiver<VideoFrame>>,

    /// ICE candidates queued by `on_ice_candidate` callbacks.
    pub ice_rx: mpsc::Receiver<IceCandidateInit>,
    ice_tx: mpsc::Sender<IceCandidateInit>,

    /// The underlying WebRTC peer connection.
    peer_connection: Arc<RTCPeerConnection>,

    /// Audio track for sending local audio to remote.
    audio_track: Option<Arc<TrackLocalStaticRTP>>,

    /// Video track for sending local video to remote.
    #[allow(dead_code)]
    video_track: Option<Arc<TrackLocalStaticRTP>>,

    /// Handle to stop audio capture task.
    audio_stop: Arc<Mutex<Option<mpsc::Sender<()>>>>,

    /// Handle to stop video capture task.
    video_stop: Arc<Mutex<Option<mpsc::Sender<()>>>>,

    _tasks: Vec<tokio::task::JoinHandle<()>>,
}

impl RtcCallSession {
    /// Create an outgoing call session. Generates SDP offer;
    /// call `set_remote_answer()` once the remote answer arrives.
    pub async fn new_outgoing(
        conv_id: String,
        video: bool,
        media: Arc<dyn MediaCapture>,
        max_kbps: Option<u64>,
    ) -> Result<Self, WebRtcError> {
        let call_id = gen_id("call");
        let state = Arc::new(Mutex::new(CallState::Outgoing {
            call_id: call_id.clone(),
            conv_id: conv_id.clone(),
        }));

        let (pc, ice_tx, ice_rx, audio_track, remote_audio_rx, tasks) =
            setup_peer_connection(&call_id).await?;

        let (audio_stop_tx, audio_stop_rx) = mpsc::channel(1);
        let (video_stop_tx, video_stop_rx) = mpsc::channel(1);

        let mut session = Self {
            call_id,
            conv_id,
            video,
            max_kbps,
            local_sdp: String::new(),
            state,
            remote_audio_rx,
            remote_video_rx: None,
            ice_rx,
            ice_tx,
            peer_connection: pc,
            audio_track,
            video_track: None,
            audio_stop: Arc::new(Mutex::new(Some(audio_stop_tx))),
            video_stop: Arc::new(Mutex::new(Some(video_stop_tx))),
            _tasks: tasks,
        };

        // Set up media capture forwarding
        session.start_media_capture(media, audio_stop_rx, video_stop_rx).await;

        // Set up ICE candidate forwarding
        session.setup_ice_forwarding().await;

        // Generate SDP offer, applying the configured bandwidth cap.
        let mut offer = session.peer_connection.create_offer(None).await
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;
        if let Some(kbps) = session.max_kbps {
            offer.sdp = inject_b_as(&offer.sdp, kbps);
        }
        session.peer_connection.set_local_description(offer.clone()).await
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;

        session.local_sdp = serde_json::to_string(&offer)
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;

        Ok(session)
    }

    /// Create an incoming call session. `remote_sdp` is the caller's offer.
    /// Generates local SDP answer.
    pub async fn new_incoming(
        call_id: String,
        conv_id: String,
        video: bool,
        remote_sdp: String,
        media: Arc<dyn MediaCapture>,
        max_kbps: Option<u64>,
    ) -> Result<Self, WebRtcError> {
        let state = Arc::new(Mutex::new(CallState::Incoming {
            call_id: call_id.clone(),
            conv_id: conv_id.clone(),
            video,
            remote_sdp: remote_sdp.clone(),
        }));

        let (pc, ice_tx, ice_rx, audio_track, remote_audio_rx, tasks) =
            setup_peer_connection(&call_id).await?;

        let (audio_stop_tx, audio_stop_rx) = mpsc::channel(1);
        let (video_stop_tx, video_stop_rx) = mpsc::channel(1);

        let mut session = Self {
            call_id,
            conv_id,
            video,
            max_kbps,
            local_sdp: String::new(),
            state,
            remote_audio_rx,
            remote_video_rx: None,
            ice_rx,
            ice_tx,
            peer_connection: pc,
            audio_track,
            video_track: None,
            audio_stop: Arc::new(Mutex::new(Some(audio_stop_tx))),
            video_stop: Arc::new(Mutex::new(Some(video_stop_tx))),
            _tasks: tasks,
        };

        // Set up media capture forwarding
        session.start_media_capture(media, audio_stop_rx, video_stop_rx).await;

        // Set up ICE candidate forwarding
        session.setup_ice_forwarding().await;

        // Set remote description (offer from caller)
        let offer: RTCSessionDescription = serde_json::from_str(&remote_sdp)
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;
        session.peer_connection.set_remote_description(offer).await
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;

        // Generate SDP answer, applying the configured bandwidth cap.
        let mut answer = session.peer_connection.create_answer(None).await
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;
        if let Some(kbps) = session.max_kbps {
            answer.sdp = inject_b_as(&answer.sdp, kbps);
        }
        session.peer_connection.set_local_description(answer.clone()).await
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;

        session.local_sdp = serde_json::to_string(&answer)
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;

        Ok(session)
    }

    /// Set the remote SDP answer (for outgoing calls).
    pub async fn set_remote_answer(&self, answer_sdp: &str) -> Result<(), WebRtcError> {
        let answer: RTCSessionDescription = serde_json::from_str(answer_sdp)
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;
        self.peer_connection.set_remote_description(answer).await
            .map_err(|e| WebRtcError::SdpError(e.to_string()))?;
        Ok(())
    }

    /// Transition to `Active` state once both SDPs have been exchanged.
    pub async fn activate(&self) {
        let mut s = self.state.lock().await;
        *s = CallState::Active {
            call_id: self.call_id.clone(),
            conv_id: self.conv_id.clone(),
        };
    }

    /// Hang up the call, transitioning to `Ended`.
    pub async fn hang_up(&self) {
        // Stop media capture
        if let Some(stop) = self.audio_stop.lock().await.take() {
            let _ = stop.send(()).await;
        }
        if let Some(stop) = self.video_stop.lock().await.take() {
            let _ = stop.send(()).await;
        }

        // Close the peer connection
        let _ = self.peer_connection.close().await;

        *self.state.lock().await = CallState::Ended;
    }

    /// Snapshot the current call state without blocking the UI thread.
    pub async fn current_state(&self) -> CallState {
        self.state.lock().await.clone()
    }

    /// Inject an external ICE candidate (from the remote peer) into the session.
    pub async fn add_remote_ice(&self, candidate: IceCandidateInit) {
        // Parse the ICE candidate and add it to the peer connection
        let ice_init = webrtc::ice_transport::ice_candidate::RTCIceCandidateInit {
            candidate: candidate.candidate,
            sdp_mid: candidate.sdp_mid,
            sdp_mline_index: candidate.sdp_mline_index,
            ..Default::default()
        };

        match self.peer_connection.add_ice_candidate(ice_init).await {
            Ok(()) => {
                tracing::info!("[WebRTC] ICE candidate added successfully");
            }
            Err(e) => {
                tracing::warn!("[WebRTC] Failed to add ICE candidate: {e}");
            }
        }
    }

    /// Get the local SDP (offer or answer) as a JSON string.
    pub fn local_sdp_json(&self) -> &str {
        &self.local_sdp
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    async fn start_media_capture(
        &mut self,
        media: Arc<dyn MediaCapture>,
        mut audio_stop_rx: mpsc::Receiver<()>,
        mut video_stop_rx: mpsc::Receiver<()>,
    ) {
        // Forward local audio to the remote peer via RTP
        if let Some(track) = &self.audio_track {
            let track = track.clone();
            let mut local_audio = media.start_audio().await;
            let media_clone = media.clone();
            self._tasks.push(tokio::spawn(async move {
                let mut sequence_number: u16 = 0;
                let ssrc: u32 = 12345;
                loop {
                    tokio::select! {
                        Some(samples) = local_audio.recv() => {
                            // Convert f32 PCM samples to i16
                            let i16_samples: Vec<i16> = samples.iter()
                                .map(|&s| (s * 32767.0).clamp(-32768.0, 32767.0) as i16)
                                .collect();

                            // Create RTP payload with proper header
                            let mut payload = Vec::with_capacity(12 + i16_samples.len() * 2);

                            // RTP Header (12 bytes)
                            // Version=2, Padding=0, Extension=0, CSRC=0, Marker=0
                            payload.push(0x80); // V=2, P=0, X=0, CC=0
                            payload.push(111);  // PT=111 (Opus)
                            // Sequence number (big-endian)
                            payload.extend_from_slice(&sequence_number.to_be_bytes());
                            // Timestamp (48kHz, big-endian)
                            let timestamp = (sequence_number as u32) * 480; // 20ms frames
                            payload.extend_from_slice(&timestamp.to_be_bytes());
                            // SSRC (big-endian)
                            payload.extend_from_slice(&ssrc.to_be_bytes());

                            // Audio payload (i16 PCM)
                            for &sample in &i16_samples {
                                payload.extend_from_slice(&sample.to_be_bytes());
                            }

                            if let Err(e) = track.write(&payload).await {
                                tracing::error!("[WebRTC] Error writing audio: {e}");
                            }
                            sequence_number = sequence_number.wrapping_add(1);
                        }
                        _ = audio_stop_rx.recv() => {
                            media_clone.stop_audio().await;
                            break;
                        }
                        else => break,
                    }
                }
            }));
        }

        // Forward local video to the remote peer via RTP
        if self.video {
            if let Some(video_track) = &self.video_track {
                let track = video_track.clone();
                match media.start_video().await {
                    Some(mut local_video) => {
                        let media_clone = media.clone();
                        self._tasks.push(tokio::spawn(async move {
                            let mut sequence_number: u16 = 0;
                            let ssrc: u32 = 67890; // Different SSRC for video
                            loop {
                                tokio::select! {
                                    Some(frame) = local_video.recv() => {
                                        // Create RTP payload with video frame data
                                        // NOTE: VP8 encoding should be added here.
                                        // The shiguredo_libvpx crate has a complex API that requires
                                        // careful integration. For now, sending raw RGBA.
                                        // In production, this would use VP8 encoding for proper
                                        // video compression and interoperability.
                                        let mut payload = Vec::with_capacity(12 + frame.rgba.len());

                                        // RTP Header (12 bytes)
                                        payload.push(0x80); // V=2, P=0, X=0, CC=0
                                        payload.push(96);   // PT=96 (VP8)
                                        payload.extend_from_slice(&sequence_number.to_be_bytes());
                                        let timestamp = (sequence_number as u32) * 900; // 30fps @ 90kHz
                                        payload.extend_from_slice(&timestamp.to_be_bytes());
                                        payload.extend_from_slice(&ssrc.to_be_bytes());

                                        // Video payload (raw frame data)
                                        payload.extend_from_slice(&frame.rgba);

                                        if let Err(e) = track.write(&payload).await {
                                            tracing::error!("[WebRTC] Error writing video: {e}");
                                        }
                                        sequence_number = sequence_number.wrapping_add(1);
                                    }
                                    _ = video_stop_rx.recv() => {
                                        media_clone.stop_video().await;
                                        break;
                                    }
                                    else => break,
                                }
                            }
                        }));
                    }
                None => {
                    tracing::warn!("[WebRTC] Video capture not available, continuing with audio only");
                    self.video = false;
                }
                }
            }
        }
    }

    async fn setup_ice_forwarding(&mut self) {
        let ice_tx = self.ice_tx.clone();

        self.peer_connection.on_ice_candidate(Box::new(move |candidate: Option<webrtc::ice_transport::ice_candidate::RTCIceCandidate>| {
            let ice_tx = ice_tx.clone();
            Box::pin(async move {
                if let Some(candidate) = candidate {
                    if let Ok(json) = candidate.to_json() {
                        let ice_candidate = IceCandidateInit {
                            candidate: json.candidate,
                            sdp_mid: json.sdp_mid,
                            sdp_mline_index: json.sdp_mline_index,
                        };
                        let _ = ice_tx.send(ice_candidate).await;
                    }
                }
            })
        }));
    }
}

// ---------------------------------------------------------------------------
// Peer connection setup
// ---------------------------------------------------------------------------

async fn setup_peer_connection(
    call_id: &str,
) -> Result<
    (
        Arc<RTCPeerConnection>,
        mpsc::Sender<IceCandidateInit>,
        mpsc::Receiver<IceCandidateInit>,
        Option<Arc<TrackLocalStaticRTP>>,
        mpsc::Receiver<AudioSamples>,
        Vec<tokio::task::JoinHandle<()>>,
    ),
    WebRtcError,
> {
    let tasks = Vec::new();

    // Create media engine and register the codecs we use (opus audio, VP8 video).
    // `MediaEngine::default()` is an empty codec table — without registration,
    // SDP offer/answer generation fails with `ErrSenderWithNoCodecs`.
    let mut media_engine = MediaEngine::default();
    media_engine.register_default_codecs()
        .map_err(|e| WebRtcError::MediaError(format!("register_default_codecs: {e}")))?;

    // Create setting engine
    let setting_engine = SettingEngine::default();

    // Create API
    let api = APIBuilder::new()
        .with_media_engine(media_engine)
        .with_setting_engine(setting_engine)
        .build();

    // Create peer connection
    let config = RTCConfiguration::default();

    let peer_connection = Arc::new(api.new_peer_connection(config).await
        .map_err(|e| WebRtcError::PeerConnectionError(e.to_string()))?);

    // Create audio track.  `clock_rate`/`channels` must match the opus codec
    // registered in the media engine so the SDP offer/answer population finds it.
    let audio_track = Arc::new(TrackLocalStaticRTP::new(
        RTCRtpCodecCapability {
            mime_type: "audio/opus".to_string(),
            clock_rate: 48000,
            channels: 2,
            ..Default::default()
        },
        format!("audio-{call_id}"),
        format!("transferd-audio-{call_id}"),
    ));

    let _audio_transceiver = peer_connection.add_transceiver_from_track(
        Arc::clone(&audio_track) as Arc<dyn TrackLocal + Send + Sync>,
        None,
    ).await.map_err(|e| WebRtcError::PeerConnectionError(e.to_string()))?;

    // ICE candidate channel
    let (ice_tx, ice_rx) = mpsc::channel(16);

    // Monitor connection state
    peer_connection.on_peer_connection_state_change(Box::new(move |state: RTCPeerConnectionState| {
        Box::pin(async move {
            tracing::info!("[WebRTC] Connection state: {:?}", state);
        })
    }));

    // Handle incoming tracks from remote peer
    let (remote_audio_tx, remote_audio_rx) = mpsc::channel(64);
    peer_connection.on_track(Box::new(move |track, _receiver, _transceiver| {
        let remote_audio_tx = remote_audio_tx.clone();
        Box::pin(async move {
            // Read RTP packets from the remote track
            loop {
                match track.read_rtp().await {
                    Ok((packet, _)) => {
                        // Parse RTP header (12 bytes minimum)
                        if packet.payload.len() < 12 {
                            continue;
                        }

                        // Extract payload (skip 12-byte RTP header)
                        let payload = &packet.payload[12..];

                        // Convert i16 PCM samples to f32
                        // The payload contains i16 samples in big-endian format
                        let samples: AudioSamples = payload
                            .as_chunks::<2>()
                            .0
                            .iter()
                            .map(|chunk| {
                                let i16_sample = i16::from_be_bytes([chunk[0], chunk[1]]);
                                i16_sample as f32 / 32767.0
                            })
                            .collect();

                        if !samples.is_empty() && remote_audio_tx.send(samples).await.is_err() {
                            tracing::debug!("[WebRTC] Remote audio channel closed");
                            break;
                        }
                    }
                    Err(e) => {
                        tracing::error!("[WebRTC] Error reading RTP: {e}");
                        break;
                    }
                }
            }
        })
    }));

    Ok((
        peer_connection,
        ice_tx,
        ice_rx,
        Some(audio_track),
        remote_audio_rx,
        tasks,
    ))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn gen_id(prefix: &str) -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos();
    format!("{prefix}-{nanos:08x}")
}

/// Convert RGBA pixel data to I420 (YUV 4:2:0) format for VP8 encoding.
#[allow(dead_code)]
fn rgba_to_i420(rgba: &[u8], width: u32, height: u32) -> Vec<u8> {
    let w = width as usize;
    let h = height as usize;
    let y_size = w * h;
    let uv_size = (w / 2) * (h / 2);

    let mut i420 = vec![0u8; y_size + uv_size * 2];

    // Convert RGBA to YUV
    for y in 0..h {
        for x in 0..w {
            let i = (y * w + x) * 4;
            let r = rgba[i] as f32;
            let g = rgba[i + 1] as f32;
            let b = rgba[i + 2] as f32;

            // Y component
            let y_val = (0.299 * r + 0.587 * g + 0.114 * b).clamp(0.0, 255.0) as u8;
            i420[y * w + x] = y_val;

            // U and V components (subsampled 2x2)
            if y % 2 == 0 && x % 2 == 0 {
                let u_val = (-0.169 * r - 0.331 * g + 0.500 * b + 128.0).clamp(0.0, 255.0) as u8;
                let v_val = (0.500 * r - 0.419 * g - 0.081 * b + 128.0).clamp(0.0, 255.0) as u8;
                let uv_idx = y_size + (y / 2) * (w / 2) + (x / 2);
                i420[uv_idx] = u_val;
                i420[uv_idx + uv_size] = v_val;
            }
        }
    }

    i420
}

// ---------------------------------------------------------------------------
// Error types
// ---------------------------------------------------------------------------

#[derive(Debug, thiserror::Error)]
pub enum WebRtcError {
    #[error("Peer connection error: {0}")]
    PeerConnectionError(String),

    #[error("SDP error: {0}")]
    SdpError(String),

    #[error("ICE error: {0}")]
    IceError(String),

    #[error("Media error: {0}")]
    MediaError(String),

    #[error("Internal error: {0}")]
    Internal(String),
}

#[cfg(test)]
mod tests {
    use super::inject_b_as;

    #[test]
    fn b_as_is_injected_after_every_media_line() {
        let sdp = "v=0\no=- 0 0 IN IP4 0.0.0.0\nm=audio 9 UDP/TLS/RTP/SAVPF 111\na=mid:0\nm=video 9 UDP/TLS/RTP/SAVPF 96\na=mid:1\n";
        let out = inject_b_as(sdp, 1500);
        assert!(out.contains("m=audio 9 UDP/TLS/RTP/SAVPF 111\nb=AS:1500\n"));
        assert!(out.contains("m=video 9 UDP/TLS/RTP/SAVPF 96\nb=AS:1500\n"));
        assert_eq!(out.matches("b=AS:1500").count(), 2);
    }

    #[test]
    fn zero_kbps_leaves_sdp_untouched() {
        let sdp = "m=audio 9 UDP/TLS/RTP/SAVPF 111\n";
        assert_eq!(inject_b_as(sdp, 0), sdp);
    }
}
