[package]
name = "transferd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "transferd"
path = "src/main.rs"

[lib]
name = "transferd_lib"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
tonic        = "0.11"
prost        = "0.12"
tokio        = { workspace = true }
futures      = { workspace = true }
parking_lot  = "0.12"
tokio-stream = { version = "0.1", features = ["net", "sync"] }
thiserror    = { workspace = true }
serde        = { workspace = true }
serde_json   = "1"
uuid         = { version = "1", features = ["v4"] }
transferd-core   = { path = "../transferd-core" }
transferd-api    = { path = "../transferd-api" }
transferd-crypto = { path = "../transferd-crypto" }
transferd-store  = { path = "../transferd-store" }
bincode          = { workspace = true }
zeroize          = { workspace = true }
rand      = { workspace = true }
bip39     = { workspace = true }
ed25519-dalek = { workspace = true }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
hex       = { workspace = true }
transferd-relay      = { path = "../transferd-relay" }
relayd               = { path = "../relayd" }
transferd-telemetry  = { path = "../transferd-telemetry" }
dirs                 = { workspace = true }
aes-gcm = { workspace = true }
argon2  = { workspace = true }
tracing = { workspace = true }
bytes   = { workspace = true }
blake3  = { workspace = true }
netdev  = "0.31"

[dev-dependencies]
futures-core     = "0.3"
tempfile         = "3"
transferd-webrtc = { path = "../transferd-webrtc", features = ["grpc-signaling"] }
tracing-subscriber = { workspace = true }
tokio-tungstenite = "0.24"

