//! Platform-specific UI entry point.
//!
//! The mobile targets (Android / iOS) receive a native window handle and use
//! the platform's GPU context (Vulkan via wgpu on Android, Metal via wgpu on
//! iOS).  On desktop (feature = "desktop") the native_window_ptr is ignored
//! and a standard OS window is created via eframe.
//!
//! This file contains only stubs that document the integration contract.
//! The full per-platform glue is generated by `cargo-mobile` and linked here.

/// Entry point called from `start_ui`.
///
/// # Arguments
/// * `daemon_addr` — gRPC address, e.g. `"http://127.0.0.1:50051"`.
/// * `native_window_ptr` — platform-specific window handle (as usize).
/// * `width`, `height` — initial surface dimensions in physical pixels.
pub fn run_ui(daemon_addr: &str, native_window_ptr: usize, width: u32, height: u32) {
    #[cfg(target_os = "android")]
    android::run(daemon_addr, native_window_ptr, width, height);

    #[cfg(target_os = "ios")]
    ios::run(daemon_addr, native_window_ptr, width, height);

    #[cfg(not(any(target_os = "android", target_os = "ios")))]
    desktop::run(daemon_addr, width, height);
}

// ---------------------------------------------------------------------------
// Android (compiled only for aarch64-linux-android etc.)
// ---------------------------------------------------------------------------

#[cfg(target_os = "android")]
mod android {
    /// Initialise an EGL/Vulkan context from the `ANativeWindow *` and run
    /// the egui event loop.  Requires `android-activity` + `winit` with the
    /// `android` platform feature, wired up by `cargo-mobile`'s generated
    /// `android/` project.
    pub fn run(addr: &str, window_ptr: usize, width: u32, height: u32) {
        // Placeholder: full implementation follows cargo-mobile scaffolding.
        // 1. Cast window_ptr back to *mut ANativeWindow.
        // 2. Create a wgpu Surface from the ANativeWindow.
        // 3. Create an egui_wgpu renderer.
        // 4. Run the egui event loop (driven by android-activity's main loop).
        // 5. Connect GrpcDaemon to addr and pass to TransferDaemonApp.
        unimplemented!("Android UI — wire up via cargo-mobile")
    }
}

// ---------------------------------------------------------------------------
// iOS (compiled only for aarch64-apple-ios etc.)
// ---------------------------------------------------------------------------

#[cfg(target_os = "ios")]
mod ios {
    /// Initialise a Metal context from the `MTKView *` and run the egui loop.
    /// Requires `winit` with `ios` platform support and a Metal device.
    pub fn run(addr: &str, window_ptr: usize, width: u32, height: u32) {
        // Placeholder: full implementation follows cargo-mobile scaffolding.
        // 1. Cast window_ptr to *mut objc::runtime::Object (MTKView).
        // 2. Create a wgpu::Surface from the MTKView layer.
        // 3. Create an egui_wgpu renderer.
        // 4. Drive rendering via the CADisplayLink callback supplied by UIKit.
        // 5. Connect GrpcDaemon to addr and pass to TransferDaemonApp.
        unimplemented!("iOS UI — wire up via cargo-mobile")
    }
}

// ---------------------------------------------------------------------------
// Desktop fallback (always compiled on non-mobile targets)
// ---------------------------------------------------------------------------

#[cfg(not(any(target_os = "android", target_os = "ios")))]
mod desktop {
    /// On desktop, ignore the native window handle and use eframe's own window.
    /// This path is exercised by the mobile-crate integration tests.
    pub fn run(addr: &str, _width: u32, _height: u32) {
        // In a test or desktop context the UI runs via eframe::run_native.
        // The mobile crate's tests call this through `start_daemon_and_connect`
        // rather than through `run_ui`, so this is a no-op placeholder.
        eprintln!("[mobile/desktop] run_ui called for addr={addr} (no-op on desktop)");
    }
}
